# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]

required = [
    "github.com/onsi/gomega",
    "github.com/spf13/viper",
    "github.com/mitchellh/mapstructure",
    "github.com/AlecAivazis/survey"
]

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.2.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.3"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.7.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"

[[constraint]]
  name = "github.com/manifoldco/promptui"
  version = "0.3.2"

[[constraint]]
  name = "github.com/AlecAivazis/survey"
  version = "1.8.2"

[[constraint]]
  name = "github.com/KexinLu/goisgit"
  version = "1.0.0"

[prune]
  go-tests = true


